version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: super_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin12!@
    ports:
      - "5435:5435"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./pgadmin_data:/var/lib/pgadmin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
